runtime: python39
entrypoint: gunicorn -b :$PORT main:main_app

instance_class: F4

env_variables:
  GOOGLE_API_KEY: "AIzaSyDg7QgSMxsUbYAX7vABCPvUN03NUocYpcY"  # Gemini API key
  GCS_BUCKET_NAME: "riitii-app-chroma-db"  # Your GCS bucket name

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
